language: python

notifications:
  email: false

sudo: required

git:
  depth: 3

env:
  - HOST_CLOUD=openstack
  - HOST_CLOUD=gce
  - HOST_CLOUD=aws


before_install:

  #Creating tmp dir
  - mkdir tmp

  #Decrypt secrets
  - >
    openssl aes-256-cbc
    -K $encrypted_92e1e3eadcc5_key
    -iv $encrypted_92e1e3eadcc5_iv
    -in keys.enc
    -out tmp/keys.tgz
    -d
  
  #Extract secrets
  - tar xzvf tmp/keys.tgz -C tmp
  
  #Add the keypair to the agent
  - eval "$(ssh-agent -s)"
  - ssh-add tmp/secret/kubenow-ci
  
  #Get secrets
  - git clone git@github.com:mcapuccini/secrets-kubenow.git tmp/secrets-kubenow

install:

  #INSTALL DEPS

  #Packer
  - >
      curl
      https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip
      > /tmp/packer.zip
  - sudo unzip /tmp/packer.zip -d /usr/bin
  - sudo chmod +x /usr/bin/packer
  
  #Jinja2 and its line interface
  - sudo pip install --upgrade pip
  - sudo pip install Jinja2
  - sudo pip install j2cli
  
before_script:

  #Source RC file
  - source tmp/secrets-kubenow/host_cloud/CityCloud.sh

  #Set necessary environmental variables

  # Variable common to all three platform
  - export current_version=$(git describe --tags --always)

  # Variable needed only for GCE
  - export playbook_dir=./temp

  #Render Templates from tmp/secrets-kubenow/packer into tmp/packer
  - env | j2 --format=env tmp/secrets-kubenow/packer/"$HOST_CLOUD".json.j2 > tmp/packer/"$HOST_CLOUD".json

script:
  - packer build -var-file=tmp/packer/"$HOST_CLOUD".json packer/build-"$HOST_CLOUD".json 