language: python

#To be removed once testing is finished
notifications:
  email: false

#branches:
#  only:
#  - master

sudo: false
dist: trusty

env:
#  - HOST_CLOUD=openstack
  - HOST_CLOUD=gce
#  - HOST_CLOUD=aws

before_install:
  #Decrypt secrets
  - >
    openssl aes-256-cbc
    -K $encrypted_92e1e3eadcc5_key
    -iv $encrypted_92e1e3eadcc5_iv
    -in keys.enc
    -out keys.tgz
    -d
  
  #Extract secrets
  - tar xzvf keys.tgz
  
  #Add the keypair to the agent
  - eval "$(ssh-agent -s)"
  - ssh-add keys/id_rsa
  
  #Get secrets
  - git clone git@github.com:mcapuccini/secrets-kubenow.git secrets-kubenow

install:
  #INSTALL DEPS

  #Packer
  - >
      curl
      https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip
      > /tmp/packer.zip

  - unzip /tmp/packer.zip
  
  #Jinja2 and its line interface
  - pip install --upgrade pip
  - pip install Jinja2
  - pip install j2cli
  
before_script:
  #Source RC file for OpenStack
  - source secrets-kubenow/host_cloud/CityCloud.sh

  #Set necessary environmental variables

  # Variable needed only for GCE
  - export playbook_dir=./

 #Get current_version, variable common to all three platforms
  #-  chmod +x script.sh
  -  source ./CI/get_current_version.sh

  #Render templates from tmp/secrets-kubenow/packer into tmp/packer
  - env | j2 --format=env secrets-kubenow/packer/"$HOST_CLOUD".json.j2 > secrets-kubenow/packer/"$HOST_CLOUD".json

script:
  - /tmp/.packer build -force -var-file=secrets-kubenow/packer/"$HOST_CLOUD".json build-"$HOST_CLOUD".json


